/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoyezi_enet_Packet_Flag */

#ifndef _Included_com_xiaoyezi_enet_Packet_Flag
#define _Included_com_xiaoyezi_enet_Packet_Flag
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
