/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoyezi_enet_EnetException */

#ifndef _Included_com_xiaoyezi_enet_EnetException
#define _Included_com_xiaoyezi_enet_EnetException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xiaoyezi_enet_EnetException_serialVersionUID
#define com_xiaoyezi_enet_EnetException_serialVersionUID -3042686055658047285LL
#undef com_xiaoyezi_enet_EnetException_serialVersionUID
#define com_xiaoyezi_enet_EnetException_serialVersionUID -3387516993124229948LL
#undef com_xiaoyezi_enet_EnetException_serialVersionUID
#define com_xiaoyezi_enet_EnetException_serialVersionUID -5753326622210863554LL
#ifdef __cplusplus
}
#endif
#endif
