/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoyezi_enet_Event */

#ifndef _Included_com_xiaoyezi_enet_Event
#define _Included_com_xiaoyezi_enet_Event
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoyezi_enet_Event
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xiaoyezi_enet_Event_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     com_xiaoyezi_enet_Event
 * Method:    peer
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoyezi_enet_Event_peer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_xiaoyezi_enet_Event
 * Method:    type
 * Signature: (Ljava/nio/ByteBuffer;)Lcom/xiaoyezi/enet/Event/Type;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoyezi_enet_Event_type
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_xiaoyezi_enet_Event
 * Method:    channelID
 * Signature: (Ljava/nio/ByteBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_com_xiaoyezi_enet_Event_channelID
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_xiaoyezi_enet_Event
 * Method:    data
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_xiaoyezi_enet_Event_data
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_xiaoyezi_enet_Event
 * Method:    packet
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoyezi_enet_Event_packet
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
