/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoyezi_enet_MutableInteger */

#ifndef _Included_com_xiaoyezi_enet_MutableInteger
#define _Included_com_xiaoyezi_enet_MutableInteger
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xiaoyezi_enet_MutableInteger_serialVersionUID
#define com_xiaoyezi_enet_MutableInteger_serialVersionUID -8742448824652078965LL
#ifdef __cplusplus
}
#endif
#endif
