/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoyezi_enet_Packet */

#ifndef _Included_com_xiaoyezi_enet_Packet
#define _Included_com_xiaoyezi_enet_Packet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoyezi_enet_Packet
 * Method:    create
 * Signature: (Ljava/nio/ByteBuffer;I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoyezi_enet_Packet_create
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_xiaoyezi_enet_Packet
 * Method:    get_bytes
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoyezi_enet_Packet_get_1bytes
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_xiaoyezi_enet_Packet
 * Method:    get_flags
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_xiaoyezi_enet_Packet_get_1flags
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_xiaoyezi_enet_Packet
 * Method:    destroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_xiaoyezi_enet_Packet_destroy
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
