/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoyezi_enet_Event_Type */

#ifndef _Included_com_xiaoyezi_enet_Event_Type
#define _Included_com_xiaoyezi_enet_Event_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
